# -*- coding: utf-8 -*-
"""sumaNaturalRecursivo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13YGksQVtTOtUd9dcbwwV1PEEJUIUTh9S
"""

class SumadorNatural:
    def __init__(self, numero):
        """
        Inicializa la clase con un número entero positivo.

        :param numero: Límite superior de la suma (desde 1 hasta este número)
        """
        self.numero = numero

    def calcular(self):
        """
        Método público que inicia el cálculo de la suma.

        :return: suma de los números desde 1 hasta self.numero
        """
        return self._suma_recursiva(self.numero)

    def _suma_recursiva(self, n):
        """
        Método recursivo privado para calcular la suma.

        :param n: número actual en la recursión
        :return: suma desde 1 hasta n
        """
        if n == 1:
            return 1
        else:
            return n + self._suma_recursiva(n - 1)


# Ejemplo de uso:
sumador = SumadorNatural(5)
print(sumador.calcular())  # Salida esperada: 15